# Generated by Django 4.2.6 on 2023-11-28 06:56

from django.db import migrations, models
import django.db.models.deletion
import v1.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_average_response_time_and_more'),
        ('orders', '0002_alter_order_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(default=v1.orders.models.Order.default_items),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vendors.vendor'),
        ),
    ]
